"""CI guard: the ORM models and the Alembic migrations must never diverge.

This is the regression test for the Phase 0 reconciliation. It fails the build
if someone edits ``api.database`` / ``api.crawler.models`` without adding a
matching migration (or relies on ``create_all()`` drift). It mirrors the CLI
``alembic check`` exactly: it upgrades a throwaway DB to head through
``migrations/env.py`` (which imports every model module and enables
``render_as_batch``) and then asserts autogenerate detects no further changes.
"""

import tempfile
from pathlib import Path
from unittest.mock import patch

from alembic import command
from alembic.config import Config

# Import every module that defines ORM models so they are registered on
# Base.metadata for the comparison (mirrors migrations/env.py).
import api.crawler.models  # noqa: F401
import api.database  # noqa: F401


def _alembic_config(db_path: Path) -> Config:
    config = Config("alembic.ini")
    config.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    return config


def test_models_stay_in_lockstep_with_migrations():
    with tempfile.TemporaryDirectory() as tmp:
        db_path = Path(tmp) / "head.db"
        with patch.dict("os.environ", {"DATABASE_URL": f"sqlite:///{db_path}"}):
            config = _alembic_config(db_path)
            command.upgrade(config, "head")
            # Raises AutogenerateDiffsDetected (with the offending ops) if the
            # models and the migration head have drifted apart.
            command.check(config)
